<section data-mpf-overlay="resetPassword">
    <section>
        <header><?= $this->getText('title'); ?><img src="/mpf-admin/images/icons/32x32/graySquareMinus.png" alt="X" class="close" /></header>
        <div>
            <form name="resetPassword" action="/mpf-admin/rest/user/resetpassword" method="PUT">
                <fieldset data-step="1">
                    <div><label for="reset_username"><?= $this->getText('username') ?></label><input type="text" name="reset_username" id="reset_username" tabindex="1" /></div>
                    <input type="submit" name="step1" value="<?= $this->getText('submit') ?>" class="gradientGreen" tabindex="2" />
                </fieldset>
                <fieldset data-step="2">
                    <div>
                        <label for="reset_password"><?= $this->getText('newPassword') ?></label>
                        <input type="password" name="reset_password" id="reset_password" tabindex="3" />
                    </div>
                    <div>
                        <label><?= \MPF\Text::byXml('login')->get('passwordStrength') ?></label>
                        <div data-mpf-password-strength="reset_password"><div data-mpf-password-strength-meter="reset_password" class="mpfStrengthLow">&nbsp;</div></div>
                        <div data-mpf-tooltip="passwordStrength">
                            <label><img src="/mpf-admin/images/icons/16x16/information.png" width="16" height="16" alt="i" /></label>
                            <section>
                                <h5><?= \MPF\Text::byXml('login')->get('passwordStrengthTitle') ?></h5>
                                <hr />
                                <?= \MPF\Text::byXml('login')->get('passwordStrengthDescription') ?>
                            </section>
                        </div>
                    </div>
                    <div><label for="reset_pwdConfirm"><?= \MPF\Text::byXml('login')->get('passwordConfirm') ?></label><input type="password" name="reset_pwdConfirm" id="reset_pwdConfirm" tabindex="4" /></div>
                    <input type="submit" name="step2" value="<?= $this->getText('submit') ?>" class="gradientGreen" tabindex="5" />
                </fieldset>
            </form>
        </div>
    </section>
</section>