<header>
    <? if (\MPF\User::bySession()): ?>
    <div class="loggedUser">
        <section>
            <span><?= \MPF\User::bySession()->getUsername() ?></span>
            <a href="/mpf-admin/rest/user/<?= \MPF\User::bySession()->getUsername() ?>/logout/?redirect=/mpf-admin/login.php" class="gradientBlueNoise"><?= $this->getText('logout', 'layout'); ?></a>
        </section>
    </div>
    <? endif; ?>
    <div>
        <section id="logo-column">
            <h1><a href="/" title="Logo made by Xavier Lebel">MyPhpFramework</a></h1>
        </section>
        <h2><?= $this->getText('title', 'layout') ?></h2>
        <br style="clear:both" />
    </div>
</header>
<hr class="gradientBlueNoise" />
